### ISSUE TITLE
NullPointerException when initialising model

### ISSUE THREAD

**Issue by richardpayne** [into-cps/INTO-CPS_Application#9]
During the initialisation of the COE I get the following exception. It appears to be related to setting the initial values as identified in the ModelDescription file.

 INFO [Thread-2] (BasicInitializer.java:76) - Entering Initialization
 INFO [Thread-2] (BasicInitializer.java:77) - Running Initialization for component: {guid}.controller
TRACE [Thread-2] (BasicInitializer.java:171) - Setting Real Map: {16=0.0, 17=0.0, 6=0.0, 7=0.0, 8=0.0, 9=0.0, 10=0.0, 11=0.0, 12=0.0, 13=0.0, 14=0.0, 15=0.0}
TRACE [Thread-2] (Util.java:92) - setRaw with comp: {guid}.controller, type: Real, indices: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.crescendo.fmi.CrescendoFmu.SetReal(CrescendoFmu.java:405)
        at org.intocps.java.fmi.service.ProtocolDriver.run(ProtocolDriver.java:106)
        at java.lang.Thread.run(Unknown Source)

**Comment by richardpayne** [comment]
Correction: this appears post-initialisation, when attempting to start simulation. The error does not always appear for the same model (I had experienced this repeatedly, closed and reopened the command line and then the simulation started fine).

**Comment by CThuleHansen** [comment]
Do you have any data for me, so I can reproduce?

**Comment by lausdahl** [comment]
@richardpayne please provide the complete model otherwise we will close this by May 6, 2016

**Comment by richardpayne** [comment]
I've not received this error for a while - I'll close it.
